name: wordly
description: Guess the WORD in six tries
publish_to: none
version: 3.0.0+30
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any

  # Design
  flutter_colorpicker: ^1.0.3

  # Localization
  intl: any
  flutter_localizations:
    sdk: flutter

  # Stream
  stream_transform: ^2.1.0
  rxdart: ^0.27.7

  # BLoC
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  flutter_bloc: ^8.1.3

  # Persisting
  shared_preferences: ^2.2.2

  # Logging
  logging: ^1.2.0
  stack_trace: ^1.11.1

  # Utils
  flutter_native_splash: ^2.3.5
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  carapacik_lints: ^1.6.0
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.5
  intl_utils: ^2.8.5

dependency_overrides:
  analyzer: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/dictionary/

flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 120

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/core/localization/translations
  output_dir: lib/src/core/localization/generated

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/icon-1024x1024.png"
  image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 23
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

  web:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"