name: wordly
description: Guess the WORD in six tries
publish_to: 'none'
version: 2.0.0+14
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  bloc: ^8.0.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_gen: ^4.3.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.1+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.6.0
  path_provider: ^2.0.11
  share_plus: ^4.0.10
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.2.0
  carapacik_lints: ^1.1.3
  flutter_gen_runner: ^4.3.0
  flutter_native_splash: ^2.2.6
  freezed: ^2.1.0+1
  icons_launcher: ^1.2.1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - google_fonts/

flutter_intl:
  enabled: true
  class_name: R
  main_locale: en
  output_dir: lib/resources/
  arb_dir: assets/l10n/

flutter_gen:
  output: lib/resources/
  integrations:
    flutter_svg: true

flutter_icons:
  image_path: 'assets/ic_logo.png'
  adaptive_icon_background: 'assets/ic_background.png'
  adaptive_icon_foreground: 'assets/ic_foreground.png'
  remove_alpha_ios: false
  remove_alpha_macos: false
  android: true
  ios: true
  linux: true
  macos: true
  web: true
  windows: true

flutter_native_splash:
  color: '#F4F7FB'
  image: assets/splash_light.png
  color_dark: '#1E1F30'
  image_dark: assets/splash_dark.png
  android: true
  ios: true
  linux: true
  macos: true
  web: true
  windows: true
  fullscreen: true
