name: wordly
description: Guess the WORD in six tries
publish_to: none
version: 3.1.2+37
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any

  # Localization
  intl: any
  flutter_localizations:
    sdk: flutter

  # BLoC
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  flutter_bloc: ^8.1.5

  # Codegen
  freezed_annotation: ^2.4.1

  # Persisting
  shared_preferences: ^2.2.3

  # Logging
  logging: ^1.2.0

  # Utils
  flutter_colorpicker:
    git: https://github.com/mchome/flutter_colorpicker
  share_plus: ^9.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.10
  carapacik_lints: ^1.8.1
  flutter_gen_runner: ^5.4.0
  #flutter_launcher_icons: ^0.13.1
  #flutter_native_splash: ^2.4.0
  freezed: ^2.5.2
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true
  assets:
    - assets/dictionary/
    - assets/fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 120

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/src/core/constant/localization/translations
  output_dir: lib/src/core/constant/localization/generated

flutter_launcher_icons:
  image_path_android: "assets/images/icon-1024x1024.png"
  image_path_ios: "assets/images/icon-borderless-1024x1024.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/images/icon-background-1024x1024.png"
  adaptive_icon_foreground: "assets/images/icon-foreground-1024x1024.png"
  min_sdk_android: 24
  web:
    generate: true
    image_path: "assets/images/icon-foreground-1024x1024.png"
    background_color: "#FFFFFF"
  macos:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
  windows:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    icon_size: 256
