name: database
description: Database-related logic
environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  drift: ^2.13.0
  path: ^1.8.3
  path_provider: ^2.1.1
  sqlite3_flutter_libs: ^0.5.17

dev_dependencies:
  build_runner: 2.4.6
  carapacik_lints: ^1.5.1
  drift_dev: ^2.13.0
